# -*- coding: utf-8 -*-
"""rule-based_chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCEHbkE5f4kxbcr79j1lUXJxFeO8l3ix
"""

import random

class BankChatbot:
    def __init__(self):
        self.greetings = ['hello', 'hi', 'hey']
        self.goodbyes = ['goodbye', 'bye', 'see you later']
        self.help_commands = ['help', 'options']
        self.services = ['services','online services','facilites','system']
        self.loan = ['loan','credit','mortgage']
        self.home = ['home']
        self.car = ['car']
        self.education = ['education']
        self.gold = ['gold']
        self.business = ['business']
        self.unknown_responses = ["I'm sorry, I didn't understand that.",
                                  "Could you please rephrase that?",
                                  "I'm not sure what you mean."]

    def handle_input(self, user_input):
        user_input = user_input.lower()
        response = ""

        if self.check_greetings(user_input):
            response = "Hello! How can I help you today?"

        elif self.check_goodbyes(user_input):
            response = "Goodbye! Have a great day."

        elif self.check_help_commands(user_input):
            response = "You can ask me about bank services and loans"

        elif self.check_loan(user_input):
            response = "Different loans provided by our bank are:\n1.Home loan\n2.Car loan\n3.Education loan\n4.Gold loan\n5.Business loan"

        elif self.check_services(user_input):
            response = "Online services of bank are:\n1.Net banking\n2.NEFT\n3.RTGS\n4.UPI"

        elif self.check_home(user_input):
            response = "Details for home loan:\n1.Interest rate for home loan is 7.8% for  and 7.6% for women\n2.Income proof documents mandatory\nFor more details visit our nearest branch"

        elif self.check_car(user_input):
            response = "Details for car loan:\n1.Interest rate for home loan is 8%\n2.Income proof documents mandatory\nFor more details visit our nearest branch"

        elif self.check_education(user_input):
            response = "Sure, let me help you with that.\nDetails for education loan:\n1.Interest rate for education loan is 6.5% for boys and 6.3% for girls\n2.Student should have completed 12th with min 60%\nFor more details visit our nearest branch"

        elif self.check_gold(user_input):
            response = "Details for gold loan:\n1.Interest rate for home loan is 8.2%\n2.Income proof and address proof documents mandatory\nFor more details visit our nearest branch"

        elif self.check_business(user_input):
            response = "Details for business loan:\n1.Interest rate for business loan is 8.5%\n2.ShopAct license and address proof documents mandatory\nFor more details visit our nearest branch"
        else:
            response = random.choice(self.unknown_responses)

        return response

    def check_greetings(self, user_input):
        return any(greeting in user_input for greeting in self.greetings)

    def check_goodbyes(self, user_input):
        return any(goodbye in user_input for goodbye in self.goodbyes)

    def check_help_commands(self, user_input):
        return any(command in user_input for command in self.help_commands)

    def check_education(self, user_input):
        return any(education in user_input for education in self.education)

    def check_services(self, user_input):
        return any(services in user_input for services in self.services)

    def check_loan(self, user_input):
        return any(loan in user_input for loan in self.loan)

    def check_home(self, user_input):
        return any(home in user_input for home in self.home)

    def check_gold(self, user_input):
        return any(gold in user_input for gold in self.gold)

    def check_car(self, user_input):
        return any(car in user_input for car in self.car)

    def check_business(self, user_input):
        return any(business in user_input for business in self.business)


# Example usage:
bank_chatbot = BankChatbot()
while True:
    user_input = input("You: ")
    if user_input.lower() == 'exit':
        print("BankChatbot: Goodbye!")
        break
    response = bank_chatbot.handle_input(user_input)
    print("BankChatbot:", response)

